# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setting up dotnet 
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: 3.1.413
          source-url: # optional
          owner: # optional
          config-file: # optional
          include-prerelease: # optional
          
  
      - name: Dotnet Publish
        # uses: EasyDesk/action-dotnet-publish@75033960a28daa2ea89e0c1d8a04754568996506
        uses: EasyDesk/action-dotnet-publish@v1.0.0
        with:
          path: # 
          output-dir: published
          build-configuration: Release # optional, default is Release
          skip-build: # optional, default is true

      # Runs a single command using the runners shell
      - name: Run a one-line script to check the results
        run: ls -l /home/runner/work/action-app/action-app/published/

      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        uses: docker/login-action@v1.10.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: # optional
          # Username used to log against the Docker registry
          username: ${{ secrets.DOCKERHUB_USER }}  # optional
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKERHUB_PASS }} # optional
          # Log out from the Docker registry at the end of a job
          logout: true # optional, default is true